### ISSUE TITLE
Unable to retrieve image details

### ISSUE THREAD

**Issue by wangweitung** [outlovecn/portainer-cn#5]
![图片](https://github.com/outlovecn/portainer-cn/assets/8080125/9ecadaeb-644c-4ca1-bb3e-1fb3a1b62a0b)

compose file:
```
version: "3"
services:
    portainer-cn:
        ports:
            - 8001:8000
            - 9000:9000
        container_name: portainer
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./data:/data
        image: outlovecn/portainer-cn:latest
        labels:
            - "com.centurylinklabs.watchtower.enable=true"
```
